CREATE TABLE VENUES (
	VENUE_ID             NUMERIC(32) IDENTITY NOT NULL PRIMARY KEY,                    
	VENUE_NAME           VARCHAR(100),
	VENUE_SEAT_CAPACITY  NUMERIC(32)
); 

CREATE TABLE SECTIONS (
	SECTION_ID            NUMERIC(32) IDENTITY NOT NULL PRIMARY KEY,                    
	VENUE_ID              NUMERIC(32),
	SECTION_NUMBER        VARCHAR(50), 
    ROW_COUNT             NUMERIC(32),
	COLUMN_COUNT          NUMERIC(32)
); 

 
CREATE TABLE EVENTS (
	EVENT_ID    		  NUMERIC(32) IDENTITY NOT NULL PRIMARY KEY,
	VENUE_ID              NUMERIC(32),
	EVENT_NAME             VARCHAR(500),
	EVENT_START_DATE_TIME  TIMESTAMP,
	EVENT_END_DATE_TIME    TIMESTAMP
);                     
                        
                         
CREATE TABLE MEMBERS(
	MEMBER_ID NUMERIC(32) IDENTITY NOT NULL PRIMARY KEY,
    VENUE_ID NUMERIC(32),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL_ADDRESS VARCHAR(50),
    GENDER VARCHAR(10),
    PHONE VARCHAR(10),
    CARD_NUMBER VARCHAR(20),
    CARD_TYPE VARCHAR(50),
    CARD_EXPIRATION_DATE DATE
);
                     
CREATE TABLE ORDERS( 
	ORDER_ID 	NUMERIC(32) IDENTITY NOT NULL PRIMARY KEY,
    EVENT_ID 	NUMERIC(32),
    MEMBER_ID 	NUMERIC(32),
    ORDER_STATUS VARCHAR(20),
    ORDER_DATE TIMESTAMP
 );
 
 
CREATE TABLE RESERVATIONS( 
	SEAT_RESERVATION_ID NUMERIC(32) IDENTITY NOT NULL PRIMARY KEY,
    ORDER_ID NUMERIC(32),
    SECTION_ID NUMERIC(32),
    ROW_NUMBER NUMERIC(32),
    SEAT_NUMBER NUMERIC(32)
);
                            

ALTER TABLE MEMBERS ADD CONSTRAINT "MEMBERS_EMAIL_ADDRESS_UQ" UNIQUE (EMAIL_ADDRESS);
ALTER TABLE ORDERS ADD CONSTRAINT "ORDERS_EVENT_ID_FK" FOREIGN KEY ("EVENT_ID") REFERENCES "EVENTS" ("EVENT_ID");

ALTER TABLE SECTIONS ADD CONSTRAINT "SECTIONS_VENUE_ID_FK" FOREIGN KEY ("VENUE_ID") REFERENCES "VENUES" ("VENUE_ID");

ALTER TABLE EVENTS ADD CONSTRAINT "EVENTS_VENUE_ID_FK" FOREIGN KEY ("VENUE_ID") REFERENCES "VENUES" ("VENUE_ID");
ALTER TABLE MEMBERS ADD CONSTRAINT "MEMBER_VENUE_ID_FK" FOREIGN KEY ("VENUE_ID") REFERENCES "VENUES" ("VENUE_ID");
ALTER TABLE ORDERS ADD CONSTRAINT "ORDERS_MEMBER_ID_FK" FOREIGN KEY ("MEMBER_ID") REFERENCES "MEMBERS" ("MEMBER_ID");

ALTER TABLE RESERVATIONS ADD CONSTRAINT "RESERVATION_SECTION_ID_FK" FOREIGN KEY ("SECTION_ID") REFERENCES "SECTIONS" ("SECTION_ID");
ALTER TABLE RESERVATIONS ADD CONSTRAINT "RESERVATION_ORDER_ID_FK"   FOREIGN KEY ("ORDER_ID")   REFERENCES "ORDERS" ("ORDER_ID");

CREATE SEQUENCE ORDERS_SEQ START WITH 98790 INCREMENT BY 1;

CREATE SEQUENCE SEAT_RESERVATION_ID_SEQ START WITH 89278 INCREMENT BY 1;
